name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install hatch
          python -m pip install -r requirements.txt
      - name: Run tests
        run: coverage run -m pytest tests/
      - name: Create report
        run: coverage xml
      - name: Upload coverage
        uses: codecov/codecov-action@v1

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
